// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3ANMJmRMrYZuN2eTrhtZhF
// Component: WlyNLIkTXwIr

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button2 from "../../Button2"; // plasmic-import: JkYce_MEgSAA/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 3ANMJmRMrYZuN2eTrhtZhF/projectcss
import sty from "./PlasmicEmptyButton.module.css"; // plasmic-import: WlyNLIkTXwIr/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: JYvICnJX2T43/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: _CSr7N7H9_ud/icon

createPlasmicElementProxy;

export type PlasmicEmptyButton__VariantMembers = {};
export type PlasmicEmptyButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicEmptyButton__VariantsArgs;
export const PlasmicEmptyButton__VariantProps = new Array<VariantPropType>();

export type PlasmicEmptyButton__ArgsType = {};
type ArgPropType = keyof PlasmicEmptyButton__ArgsType;
export const PlasmicEmptyButton__ArgProps = new Array<ArgPropType>();

export type PlasmicEmptyButton__OverridesType = {
  buttonEmpty?: Flex__<typeof Button2>;
  text?: Flex__<"div">;
};

export interface DefaultEmptyButtonProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicEmptyButton__RenderFunc(props: {
  variants: PlasmicEmptyButton__VariantsArgs;
  args: PlasmicEmptyButton__ArgsType;
  overrides: PlasmicEmptyButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Button2
      data-plasmic-name={"buttonEmpty"}
      data-plasmic-override={overrides.buttonEmpty}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.buttonEmpty)}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Reserva una clase"}
      </div>
    </Button2>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  buttonEmpty: ["buttonEmpty", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  buttonEmpty: typeof Button2;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEmptyButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEmptyButton__VariantsArgs;
    args?: PlasmicEmptyButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicEmptyButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicEmptyButton__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEmptyButton__ArgProps,
          internalVariantPropNames: PlasmicEmptyButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEmptyButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "buttonEmpty") {
    func.displayName = "PlasmicEmptyButton";
  } else {
    func.displayName = `PlasmicEmptyButton.${nodeName}`;
  }
  return func;
}

export const PlasmicEmptyButton = Object.assign(
  // Top-level PlasmicEmptyButton renders the root element
  makeNodeComponent("buttonEmpty"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicEmptyButton
    internalVariantProps: PlasmicEmptyButton__VariantProps,
    internalArgProps: PlasmicEmptyButton__ArgProps
  }
);

export default PlasmicEmptyButton;
/* prettier-ignore-end */
