// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3ANMJmRMrYZuN2eTrhtZhF
// Component: 7wO7KzItzftQ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button2 from "../../Button2"; // plasmic-import: JkYce_MEgSAA/component
import CustomButton from "../../CustomButton"; // plasmic-import: 3khqwttOo2Fs/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 3ANMJmRMrYZuN2eTrhtZhF/projectcss
import sty from "./PlasmicCustomButton2.module.css"; // plasmic-import: 7wO7KzItzftQ/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: JYvICnJX2T43/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: _CSr7N7H9_ud/icon

createPlasmicElementProxy;

export type PlasmicCustomButton2__VariantMembers = {};
export type PlasmicCustomButton2__VariantsArgs = {};
type VariantPropType = keyof PlasmicCustomButton2__VariantsArgs;
export const PlasmicCustomButton2__VariantProps = new Array<VariantPropType>();

export type PlasmicCustomButton2__ArgsType = {};
type ArgPropType = keyof PlasmicCustomButton2__ArgsType;
export const PlasmicCustomButton2__ArgProps = new Array<ArgPropType>();

export type PlasmicCustomButton2__OverridesType = {
  root?: Flex__<typeof Button2>;
  customButton?: Flex__<typeof CustomButton>;
};

export interface DefaultCustomButton2Props {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCustomButton2__RenderFunc(props: {
  variants: PlasmicCustomButton2__VariantsArgs;
  args: PlasmicCustomButton2__ArgsType;
  overrides: PlasmicCustomButton2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Button2
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
      onClick={async event => {
        const $steps = {};

        $steps["goToPage"] = true
          ? (() => {
              const actionArgs = {};
              return (({ destination }) => {
                if (
                  typeof destination === "string" &&
                  destination.startsWith("#")
                ) {
                  document
                    .getElementById(destination.substr(1))
                    .scrollIntoView({ behavior: "smooth" });
                } else {
                  __nextRouter?.push(destination);
                }
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["goToPage"] != null &&
          typeof $steps["goToPage"] === "object" &&
          typeof $steps["goToPage"].then === "function"
        ) {
          $steps["goToPage"] = await $steps["goToPage"];
        }
      }}
    >
      <CustomButton
        data-plasmic-name={"customButton"}
        data-plasmic-override={overrides.customButton}
        className={classNames("__wab_instance", sty.customButton)}
      />
    </Button2>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "customButton"],
  customButton: ["customButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof Button2;
  customButton: typeof CustomButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCustomButton2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCustomButton2__VariantsArgs;
    args?: PlasmicCustomButton2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCustomButton2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCustomButton2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCustomButton2__ArgProps,
          internalVariantPropNames: PlasmicCustomButton2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCustomButton2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCustomButton2";
  } else {
    func.displayName = `PlasmicCustomButton2.${nodeName}`;
  }
  return func;
}

export const PlasmicCustomButton2 = Object.assign(
  // Top-level PlasmicCustomButton2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    customButton: makeNodeComponent("customButton"),

    // Metadata about props expected for PlasmicCustomButton2
    internalVariantProps: PlasmicCustomButton2__VariantProps,
    internalArgProps: PlasmicCustomButton2__ArgProps
  }
);

export default PlasmicCustomButton2;
/* prettier-ignore-end */
